// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiSignalRBackend.WebAPI.Data;

#nullable disable

namespace TaxiSignalRBackend.WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212205815_Tables")]
    partial class Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TaxiSignalRBackend.WebAPI.Models.Driver", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxiStandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxiStandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("TaxiSignalRBackend.WebAPI.Models.TaxiRequest", b =>
                {
                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverPlate")
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedFare")
                        .HasColumnType("REAL");

                    b.Property<double>("FromLat")
                        .HasColumnType("REAL");

                    b.Property<double>("FromLng")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxiStandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ToLat")
                        .HasColumnType("REAL");

                    b.Property<double>("ToLng")
                        .HasColumnType("REAL");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.ToTable("TaxiRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
